services:
    pDonatas\Prettier\PrettierTask:
        class: \pDonatas\Prettier\PrettierTask
        arguments:
            - "@process_builder"
            - "@formatter.raw_process"
        tags:
            - { name: grumphp.task, task: prettier }
